### PR TITLE
Fix notch filter bug and streamline preprocessing

### PR DESCRIPTION
**Pull request by emilyps14**
Resolves Issue #99 
1. Fixing bug where notch filtering operates on the channels dimension rather than the time dimension.
2. Remove padding to a power of 2 in the preprocessing (since resample and apply_linenoise_notch further pad the signal and break the power of 2 anyway).

### CODE REVIEW

**Comment by luiztauffer** [comment]
It seems to be working and running fast again, tested on my machine, good job @emilyps14 !
Now two things:

1. These lines are here to test if the function was called to save LFP data on a file that already has it, in this case it would just return it. I think the only time we call this function on ecogvis is to generate LFP after we tested for it, so I believe it is safe to remove this if condition:
https://github.com/catalystneuro/ecogVIS/blob/49f47ace8d6314f5a8f68d9a760ab91ae0a8ed9e/ecogvis/signal_processing/processing_data.py#L138-L145

2. For the tests, you mentioned you had a specific data you'd like to use in an included csv file (instead of garbage data in the code) and I agree that would be much better! Do you have this file already? I think it would be ideal to merge this PR with the tests

**Comment by emilyps14** [comment]
> It seems to be working and running fast again, tested on my machine, good job @emilyps14 !
> Now two things:
> 
> 1. These lines are here to test if the function was called to save LFP data on a file that already has it, in this case it would just return it. I think the only time we call this function on ecogvis is to generate LFP after we tested for it, so I believe it is safe to remove this if condition:
https://github.com/catalystneuro/ecogVIS/blob/49f47ace8d6314f5a8f68d9a760ab91ae0a8ed9e/ecogvis/signal_processing/processing_data.py#L138-L145

Agreed (I didn't add that comment, it was already there. Based on git blame I think Joe was the one who wrote it) -- the function doesn't return the data anyway, so those lines aren't doing anything.
    
> 2. For the tests, you mentioned you had a specific data you'd like to use in an included csv file (instead of garbage data in the code) and I agree that would be much better! Do you have this file already? I think it would be ideal to merge this PR with the tests

I was picturing making dummy data the same way (white noise with np.random.rand), but it needs to be longer for the downsampling testing. Typically we downsample from 3051.75 Hz (non-integer is weird but the code can handle it now and will need to continue to do so) to 400 Hz, so we need something like 1 second of data sampled at 3051.75 Hz (not big, but too big to copy and paste into the code without being cumbersome). It occurred to me that it would make sense to store the dummy data in a nwb file, so we can just load it. Then the only question is how to store the solutions to the test cases (at 400 Hz). Currently they are stored in the tests themselves but maybe we could have a "correct processed" nwb file to compare the results to?

How about this: we have one nwb file that we include in `signal_processing/tests` that is fully, correctly preprocessed. Then the code makes a copy with only the raw data (white noise), processes it through the three steps (preprocess_raw_data, spectral_decomposition, high_gamma_estimation) and compares the regenerated data interfaces to the original.

**Comment by emilyps14** [comment]
OK I updated the PR:
1. Raise a warning if preprocess_raw_data is run for a file where LFP already exists, and don't run the preprocessing (if we just removed the if statement and someone ran it on a file with an LFP, it would error out at the very end after running all of the preprocessing)
2. Refactor to work with a new dummy data file, `example_ecephys.nwb`. Since the tests depend on each other, I've put them all in one master testing function `ProcessingDataTestCase.test_processing()`, which runs them in order.

**Comment by luiztauffer** [comment]
the tests passed here, once we decide what to do in cases where LFP already exists, we can merge it

**Comment by emilyps14** [comment]
@luiztauffer Yeah I agree that we shouldn't raise an error. The way I set it up, `preprocess_raw_data` will raise a RuntimeWarning if `nwb.processing['ecephys'].data_interfaces['LFP']` already exists, with the text `LFP data already exists in the nwb file. Skipping preprocessing.`. It doesn't need to return the data, since the function doesn't return anything under normal circumstances. So the warning will be thrown, the preprocessing will be skipped, and the upstream program can continue with the existing `LFP` data. Am I missing something?

**Comment by emilyps14** [comment]
In the test cases, we definitely do want it to raise an error if `LFP` already exists, because if it skips the preprocessing it won't test it.

**Comment by luiztauffer** [comment]
> @luiztauffer Yeah I agree that we shouldn't raise an error. The way I set it up, `preprocess_raw_data` will raise a RuntimeWarning if `nwb.processing['ecephys'].data_interfaces['LFP']` already exists, with the text `LFP data already exists in the nwb file. Skipping preprocessing.`. It doesn't need to return the data, since the function doesn't return anything under normal circumstances. So the warning will be thrown, the preprocessing will be skipped, and the upstream program can continue with the existing `LFP` data. Am I missing something?

Yes, if you `raise` it will stop the process, even if it is a Warning and not an Error. I committed a change to that using `warnings` library that should do it.
About the tests, we have complete control of what calls the preprocessing function, right? It shouldn't be a problem there if we write the tests right

**Comment by emilyps14** [comment]
> Yes, if you `raise` it will stop the process, even if it is a Warning and not an Error. I committed a change to that using `warnings` library that should do it.

Ah, ok, I understand now. I should have tested it. Thanks for making the change.

> About the tests, we have complete control of what calls the preprocessing function, right? It shouldn't be a problem there if we write the tests right

True. 

Thanks for all your help with this PR @luiztauffer!

**Pull request merged**
